// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUjSEhFTxuN4GtOtwkIJrmywXbDdN-cc',
    appId: '1:353483962816:android:bd0ce9fc55f4ee2d08b025',
    messagingSenderId: '353483962816',
    projectId: 'my-iot-cb9b4',
    databaseURL: 'https://my-iot-cb9b4-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-cb9b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8xupIwm7URXLwRe72EDP2AXT1TVLqN0',
    appId: '1:353483962816:ios:139f73c20681705908b025',
    messagingSenderId: '353483962816',
    projectId: 'my-iot-cb9b4',
    databaseURL: 'https://my-iot-cb9b4-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-cb9b4.appspot.com',
    iosClientId: '353483962816-uogp5c951aoc8tm4kbdf0jpmoqj09up1.apps.googleusercontent.com',
    iosBundleId: 'com.example.soilTest',
  );
}
